In [1]:
import numpy as np
from itertools import repeat

base_size = 16
grid_size = 32
interp_scale = 1.0

grid_size = tuple(repeat(grid_size, 2))

grid_h = np.arange (grid_size[0], dtype=np.float32) / (grid_size[0] / base_size) / interp_scale
grid_w = np.arange (grid_size[1], dtype=np.float32) / (grid_size[1] / base_size) / interp_scale

In [12]:
grid_h, grid_w
grid = np.meshgrid(grid_w, grid_h)

In [ ]:
# grid[0] stores x (width) co-ordinate grid[1] stores y (height) co-ordinates
grid[0].shape, grid[1].shape

((32, 32), (32, 32))

In [4]:

grid[0]

array([[ 0. ,  0.5,  1. , ..., 14.5, 15. , 15.5],
       [ 0. ,  0.5,  1. , ..., 14.5, 15. , 15.5],
       [ 0. ,  0.5,  1. , ..., 14.5, 15. , 15.5],
       ...,
       [ 0. ,  0.5,  1. , ..., 14.5, 15. , 15.5],
       [ 0. ,  0.5,  1. , ..., 14.5, 15. , 15.5],
       [ 0. ,  0.5,  1. , ..., 14.5, 15. , 15.5]], dtype=float32)

- meshgrid repeats the row one time for each value in B
- column in B one time for each value in a (B is basically columns)
- representation :
- (1,4) (2, 4)
- (1,5)  (2, 5)
- (1,6)  (2, 6)

In [5]:
a = [1,2]
b = [4, 5, 6]

c = np.meshgrid(a,b)
c

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[4, 4],
        [5, 5],
        [6, 6]])]

In [6]:
final_grid = np.stack(c, axis=0)

In [7]:
final_grid.shape

(2, 3, 2)

- final_grid[0] is the x matrix
- final_grid[1] is the y matrix

In [17]:
final_grid.shape

(2, 3, 2)

In [23]:
final_grid[0], final_grid[1]

(array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[4, 4],
        [5, 5],
        [6, 6]]))